// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:epurse/features/dashboard/data/atm_locator/model/local_atm_model.dart';
import 'package:epurse/features/payments/data/check_beneficiary/model/local_beneficiary_model.dart';
import 'package:epurse/features/registration/data/register4_address/models/address_data_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressDataModelAdapter());
    registerAdapter(LocalAtmModelAdapter());
    registerAdapter(LocalBeneficiaryModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AddressDataModelAdapter());
    registerAdapter(LocalAtmModelAdapter());
    registerAdapter(LocalBeneficiaryModelAdapter());
  }
}
